#!/bin/bash

git checkout -b gh-pages
git merge master
git push origin gh-pages
git checkout master

echo 'published on http://roylines.co.uk/how-i-learned-to-stop-worrying-and-love-the-failed-build'
